[package]
name = "recs"
version = "0.1.0"
authors = ["Henrik Paul KÃ¶hn <hpkoehn@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"anymap" = "0.12.1"
